// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sggnkmajejiqkniclyaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnZ25rbWFqZWppcWtuaWNseWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzIxNjksImV4cCI6MjA2MDgwODE2OX0.ksjEsBfJQNzH1Ze9_-7yFZMPtTLZIDHoxhwNkG3TE4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);